version: '3'

services:
  mineru-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped 